
# This file was *autogenerated* from the file mage/tests/ecdsa_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_11279326 = Integer(11279326); _sage_const_182 = Integer(182); _sage_const_100 = Integer(100); _sage_const_85518893674295321206118380980485522083 = Integer(85518893674295321206118380980485522083); _sage_const_1 = Integer(1); _sage_const_95051 = Integer(95051); _sage_const_233970423115425145524320034830162017933 = Integer(233970423115425145524320034830162017933)
import unittest
from mage import ecdsa

F = FiniteField(_sage_const_233970423115425145524320034830162017933 )
E = EllipticCurve(F, [-_sage_const_95051 ,_sage_const_11279326 ])
g = E(_sage_const_182 , _sage_const_85518893674295321206118380980485522083 )

class TestECDSA(unittest.TestCase):

    def test_ecdsa(self):
        for i in range(_sage_const_100 ):
            kp = ecdsa.ECDSAKeyPair(E, g)
            mes = "allo"
            r,s = kp.sign(mes)
            assert kp.verify(mes, r,s)
            assert not kp.verify("hello", r,s)

    def test_ecdsa_with_nonce(self):
        for i in range(_sage_const_100 ):
            kp = ecdsa.ECDSAKeyPair(E, g)
            mes = "allo"
            r,s = kp.sign(mes, randint(_sage_const_1 ,kp.N))
            assert kp.verify(mes, r,s)
            assert not kp.verify("hello", r,s)


if __name__ == '__main__':
    unittest.main()

